[workspace]
resolver = "2"
members = [
    "crates/librqbit",
    "crates/gnostr-bits",
    "crates/buffers",
    "crates/clone_to_owned",
    "crates/bencode",
    "crates/sha1w",
    "crates/librqbit_core",
    "crates/peer_binary_protocol",
    "crates/dht",
    "crates/upnp",
    "crates/tracker_comms",
]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
debug = true

[profile.release-github]
inherits = "release"
debug = false
