name: Run tests

on:
  push:
    branches: ["main", "master", "*", "*/*"]
  pull_request:
    branches: ["main", "master"]

  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  check-rust-compat:
    runs-on: [ ubuntu-latest ]
    strategy:
      matrix:
        rust_version: ["1.72", "1.73", "1.74"]
    steps:
      - name: rustup toolchain install ${{ matrix.rust_version }}
        run: |
          rustup toolchain install ${{ matrix.rust_version }}
      - uses: actions/checkout@v2
      - run: rustup override set ${{ matrix.rust_version }}
      - name: cargo check
        run: cargo check
      - name: Run tests
        run: cargo test
  test:
    runs-on: [ ubuntu-latest]#, macos-latest ]#, windows-latest ]
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - name: Run tests
        run: cargo test
